In [1]:
# -*- coding:utf-8 -*-
import tensorflow as tf
from tensorflow import keras
import numpy as np
import random
import cv2
import os

orignal =[]
prediction = []

In [2]:
#Read all test videos
f= 'sample_images_RA'
Test_videos =[]
test_list = open('Labels/test.txt','r')
for line in test_list:
    name = line.split(" ")[0]
    orignal.append(line.split(" ")[-1])
    Test_videos.append(f+"/"+name)
    

In [3]:
#To load pre-trained model, trained on 5 classes 
model = tf.keras.models.load_model('trained Models/model_C3D.h5',compile=False)
#model.summary()


In [29]:
#Five class labels
labels1 = {0: 'fighting', 1: 'vandalism',2: '0normal',3: 'shooting',4: 'hockeyfight'}

#two classes labesl
labels0 ={0:'normal', 1:'abnormal'}

In [26]:
#0normal videos from 0 to 39
#fighting videos from 40 to 54
#shooting videos from 55 to 69
#vandalism videos from 70 to 84
path =Test_videos[78]
path

'sample_images_RA/vandalism/2Vandalism044_x264'

In [27]:
images = os.listdir(path)
vid = []
for img in images:
    img_path=path +"/"+img
    img2 = cv2.imread(img_path)
    img2= cv2.cvtColor(img2, cv2.COLOR_BGR2RGB)
    vid.append(cv2.resize(img2, (112, 112)))
vid = np.array(vid, dtype=np.float32)


In [28]:
result=[]
result_prob=[]
for i in range(0,len(vid),32):
    X = vid[i:i+32].transpose((2,1,0,3))
    output = model.predict_on_batch(np.array([X]))
    result_prob.append(output)
    str1=labels1[np.argmax(output)]
    print(output,str1)
    if str1=='vandalism' or str1 == 'fighting' or str1=='shooting' or str1=='hockeyfight':
        result.append(labels0[1])
    else:
        result.append(labels0[0])

[[9.8741849e-16 9.8198688e-01 0.0000000e+00 1.8013181e-02 0.0000000e+00]] fighting
[[0. 1. 0. 0. 0.]] fighting
[[0. 1. 0. 0. 0.]] fighting
[[0. 1. 0. 0. 0.]] fighting
[[0. 1. 0. 0. 0.]] fighting
[[0. 1. 0. 0. 0.]] fighting
[[0. 1. 0. 0. 0.]] fighting
[[0. 1. 0. 0. 0.]] fighting
[[0.0000000e+00 3.8270486e-16 0.0000000e+00 1.0000000e+00 0.0000000e+00]] shooting
[[0.0000000e+00 4.5806243e-30 0.0000000e+00 1.0000000e+00 0.0000000e+00]] shooting
[[0.        0.2087051 0.        0.7912949 0.       ]] shooting
[[0.000000e+00 1.104377e-07 0.000000e+00 9.999999e-01 0.000000e+00]] shooting
[[0.000000e+00 4.669215e-11 0.000000e+00 1.000000e+00 0.000000e+00]] shooting
[[0.0000000e+00 1.0000000e+00 0.0000000e+00 3.7782827e-37 0.0000000e+00]] fighting
[[7.5737857e-29 1.0000000e+00 8.1850905e-22 0.0000000e+00 0.0000000e+00]] fighting
[[0. 1. 0. 0. 0.]] fighting
[[0. 1. 0. 0. 0.]] fighting
[[0. 0. 1. 0. 0.]] 0normal
[[0. 0. 1. 0. 0.]] 0normal
[[0. 0. 1. 0. 0.]] 0normal
[[0. 0. 1. 0. 0.]] 0normal
[[0. 0

In [10]:
result

['abnormal', 'abnormal', 'abnormal', 'abnormal', 'abnormal', 'abnormal']

In [ ]:
#if Else code for five classes

In [ ]:
result=[]
result_prob=[]
for i in range(0,len(vid),32):
    X = vid[i:i+32].transpose((1,2,0,3))
    output = model.predict_on_batch(np.array([X]))
    result_prob.append(output)
    str1=labels1[np.argmax(output)]
    print(str1)
    if str1=='vandalism' or str1 == 'fighting' or str1=='shooting' or str1=='hockeyfight':
        result.append(labels0[1])
    else:
        result.append(labels0[0])

In [29]:
# Video Code

In [36]:
import cv2
import numpy as np
cap = cv2.VideoCapture('labels/fight.mp4')
vid = []
while True:
    ret, img = cap.read()
    if not ret:
        break
    vid.append(cv2.resize(img, (112, 112)))
vid = np.array(vid, dtype=np.float32)


In [ ]:
result=[]
result_prob=[]
for i in range(0,len(vid),32):
    X = vid[i:i+32].transpose((1,2,0,3))
    output = model.predict_on_batch(np.array([X]))
    result_prob.append(output)
    output = np.argmax(output)
    result.append(labels[output])
