In [9]:
# -*- coding:utf-8 -*-
import tensorflow as tf
from tensorflow import keras
import numpy as np
import random
import cv2
import os

orignal =[]
prediction = []

In [10]:
#Read all test videos
f= 'sample_images_RA'
Test_videos =[]
test_list = open('Labels/test.txt','r')
for line in test_list:
    name = line.split(" ")[0]
    orignal.append(line.split(" ")[-1])
    Test_videos.append(f+"/"+name)
    

In [12]:
#To load pre-trained model, trained on 5 classes 
model = tf.keras.models.load_model('Trained Models/model_Q3D.h5',compile=False)
#model.summary()


Model: "ResNet_NLP3DC"
__________________________________________________________________________________________________
 Layer (type)                   Output Shape         Param #     Connected to                     
 input_1 (InputLayer)           [(None, 112, 112, 3  0           []                               
                                2, 3)]                                                            
                                                                                                  
 zero_padding3d_1 (ZeroPadding3  (None, 118, 118, 38  0          ['input_1[0][0]']                
 D)                             , 3)                                                              
                                                                                                  
 conv1 (Conv3D)                 (None, 56, 56, 16,   65920       ['zero_padding3d_1[0][0]']       
                                64)                                                   

In [4]:
#two classes labesl
labels0 ={0:'abnormal', 1:'normal'}

In [6]:
#0normal videos from 0 to 39
#fighting videos from 40 to 54
#shooting videos from 55 to 69
#vandalism videos from 70 to 84
path =Test_videos[45]
path

'sample_images_RA/fighting/2Fighting007_x264'

In [7]:
images = os.listdir(path)
vid = []
for img in images:
    img_path=path +"/"+img
    img2 = cv2.imread(img_path)
    img2= cv2.cvtColor(img2, cv2.COLOR_BGR2RGB)
    vid.append(cv2.resize(img2, (112, 112)))
vid = np.array(vid, dtype=np.float32)


In [8]:
result=[]
length =len(vid)
for i in range(0,len(vid),32):
    if i+32<=length:
        X = vid[i:i+32].transpose((1,2,0,3))
        output = model.predict_on_batch(np.array([X]))
        result.append(labels0[np.argmax(output)])
        print(output,labels0[np.argmax(output)])

[[0.5006589 0.4993411]] abnormal
[[0.49969202 0.5003079 ]] normal
[[0.49773777 0.5022622 ]] normal
[[0.5020863  0.49791372]] abnormal
[[0.50569373 0.49430627]] abnormal
[[0.4945318  0.50546813]] normal
[[0.49937084 0.5006291 ]] normal
[[0.5042879  0.49571213]] abnormal
[[0.5015161 0.4984839]] abnormal
[[0.5042791  0.49572095]] abnormal
[[0.4990791  0.50092083]] normal
[[0.50060254 0.49939746]] abnormal
[[0.49805924 0.5019408 ]] normal
[[0.5063648  0.49363512]] abnormal
[[0.5003401  0.49965984]] abnormal
[[0.5030553 0.4969447]] abnormal
[[0.50181127 0.4981888 ]] abnormal
[[0.49956366 0.5004363 ]] normal
[[0.49655557 0.5034444 ]] normal
[[0.49598098 0.504019  ]] normal
[[0.494942 0.505058]] normal
[[0.4996243 0.5003757]] normal
[[0.50211734 0.49788263]] abnormal
[[0.49986333 0.50013673]] normal
[[0.49795   0.5020499]] normal
[[0.50456405 0.49543592]] abnormal
[[0.5022581  0.49774188]] abnormal
[[0.5019445  0.49805543]] abnormal
[[0.50562644 0.4943735 ]] abnormal
[[0.50193137 0.4980687 ]]

In [671]:
result

['abnormal',
 'abnormal',
 'abnormal',
 'abnormal',
 'abnormal',
 'abnormal',
 'abnormal']